#!/usr/bin/env bash

# Setup a virtual environment and run the program

#
# Copyright 2022 Marcus Behel
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.

# 2. Redistributions in binary form must reproduce the above copyright notice, 
# this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

# 3. Neither the name of the copyright holder nor the names of its contributors 
# may be used to endorse or promote products derived from this software without specific prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
# THE POSSIBILITY OF SUCH DAMAGE.
#


# Get directory of this script and change to that directory
DIR=$(realpath $(dirname "$0"))
pushd "$DIR" > /dev/null

# Make sure python3 installed
type -P python3 >/dev/null 2>&1

if [[ $? != 0 ]]; then 
    echo "python3 not installed. Install python3 using distribution packages. On Ubuntu this can be done by running 'sudo apt-get install python3'"
    exit 1
fi

# Make sure pip installed
python3 -m pip > /dev/null 2>&1
if [[ $? != 0 ]]; then
    echo "pip not installed. Install pip using distribution packages. On Ubuntu this can be done by running 'sudo apt-get install python3-pip'"
    popd
    exit 1
fi

# make sure venv installed
python3 -m venv > /dev/null 2>&1
if [[ $? != 2 ]]; then
    echo "venv not installed. Install venv using distribution packages. On Ubuntu this can be done by running 'sudo apt-get install python3-venv'"
    popd
    exit 1
fi

# Create virtual environment if none exists
if [[ ! -d env ]]; then
    python3 -m venv env
    source env/bin/activate
    python -m pip install -r requirements.txt
    deactivate
fi

# Run app in virtual environment
source env/bin/activate
python src/main.py

# Restore original working directory on exit
popd > /dev/null
