name: Build Linux
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: python3 -m pip install -r requirements.txt
      - run: python3 compile.py
      - run: pyinstaller ./src/main.py --onefile --name CFModpackImporter
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/*
          retention-days: 1