name: Build Linux
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: ./build_linux.sh
      - uses: actions/upload-artifact@v2
        with:
          name: dist_linux64.zip
          path: ./dist/CFModpackImporter_Linux64.zip
          retention-days: 1