name: Build Windows
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: python -m pip install setuptools wheel
      - run: python -m pip install -r requirements.txt
      - run: python compile.py
      - run: pyinstaller .\src\main.py --onefile --name CFModpackImporter --icon=res/icon.ico  --windowed
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/*
          retention-days: 1