name: Build Linux
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: python3 -m pip install --upgrade -r requirements.txt
      - run: python3 -m pip install --upgrade cx_Freeze
      - run: python3 compile.py
      - run: python3 setup.py build --build-exe dist/CFModpackImporter
      - working-directory: dist
        run: zip -r dist.zip CFModpackImporter/
      - uses: actions/upload-artifact@v2
        with:
          name: dist_linux
          path: ./dist/dist.zip
          retention-days: 1