name: Build Linux (x64)
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: python --version
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install pyinstaller
      - run: python compile.py
      - run: pyinstaller ./src/main.py --onefile --windowed --name CFModpackImporter --icon=res/icon.png
      - uses: actions/upload-artifact@v2
        with:
          name: CFModpackImporter_Linux_x64
          path: ./dist/*
          retention-days: 1