name: Build macOS (x64)
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: python --version
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install pyinstaller
      - run: python compile.py
      - run: pyinstaller ./src/main.py --windowed --name CFModpackImporter --icon=res/icon.icns --osx-bundle-identifier=com.mb3hel.cfmodpackimporter
      - working-directory: dist
        run: zip CFModpackImporter_macOS_x64.zip -r CFModpackImporter.app
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/CFModpackImporter_macOS_x64.zip
          retention-days: 1