name: Build Linux (any)
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: python -m pip install -r requirements.txt
      - run: python compile.py
      - run: mkdir linux_src_package/CFModpackImporter
      - run: cp linux_src_package/CFModpackImporterStarter linux_src_package/CFModpackImporter/CFModpackImporter
      - run: cp -r src/ linux_src_package/CFModpackImporter/
      - run: cp res/icon.png linux_src_package/CFModpackImporter/
      - run: cp requirements.txt linux_src_package/CFModpackImporter/
      - working-directory: linux_src_package
        run: zip CFModpackImporter_Linux_any.zip -r CFModpackImporter
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./linux_src_package/CFModpackImporter_Linux_any.zip
          retention-days: 1