name: Build Windows (x86)
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x86'
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install pyinstaller
      - run: python compile.py
      - run: pyinstaller ./src/main.py --onefile --windowed --name CFModpackImporter --icon=res/icon.ico
      - uses: actions/upload-artifact@v2
        with:
          name: CFModpackImporter_Windows_x86
          path: ./dist/*
          retention-days: 1